/* 테이블 생성 */
CREATE TABLE IF NOT EXISTS `as_test` (
  `id` INT(10) UNSIGNED DEFAULT NULL,
  `접수번호` BIGINT(20) UNSIGNED DEFAULT NULL,
  `접수자` CHAR(3) DEFAULT NULL,
  `주민번호` CHAR(15) DEFAULT NULL,
  `접수시간` TIME DEFAULT NULL,
  `처리시간` INT(10) UNSIGNED DEFAULT NULL,
  `접수방법` VARCHAR(10) DEFAULT NULL,
  `고장형태` VARCHAR(10) DEFAULT NULL,
  `수리여부` CHAR(1) DEFAULT NULL
);

TRUNCATE TABLE `as_test`;

/* 파일로부터 자료입력 */
LOAD DATA LOCAL INFILE 'C:/as_test.txt'
INTO TABLE as_test
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '\"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
